version: "3.9"

services:
  backend:
    build: ./server
    container_name: backend
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "5173:80"   # Map port 80 inside nginx to 5173 on host
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
